// exerciseDb.js

export const exercises = [
  {
    id: 1,
    name: "Wyciskanie sztangi leżąc",
    description: "Klasyczne ćwiczenie na rozwój klatki piersiowej i tricepsów.",
    picture: require('../GymRad/assets/exercises_icons/bench-press.png'),
  },
  {
    id: 2,
    name: "Martwy ciąg",
    description: "Ćwiczenie wielostawowe angażujące plecy, nogi i pośladki.",
    picture: require('../GymRad/assets/exercises_icons/deadlift.png'),  
  },
  {
    id: 3,
    name: "Przysiady ze sztangą",
    description: "Podstawowe ćwiczenie na rozwój mięśni nóg i pośladków.",
    picture: require('../GymRad/assets/exercises_icons/barbell_squat.png'),
  },
  {
    id: 4,
    name: "Podciąganie na drążku",
    description: "Ćwiczenie rozwijające mięśnie pleców i ramion.",
    picture: require('../GymRad/assets/exercises_icons/pull_up.png'),
  },
  {
    id: 5,
    name: "Pompki klasyczne",
    description: "Uniwersalne ćwiczenie na klatkę piersiową, barki i tricepsy.",
    picture: require('../GymRad/assets/exercises_icons/push_up.png'),
  },
  {
    id: 6,
    name: "Wiosłowanie sztangą",
    description: "Ćwiczenie budujące mięśnie grzbietu i ramion.",
    picture: require('../GymRad/assets/exercises_icons/barbell_row.png'),
  },
  {
    id: 7,
    name: "Wyciskanie żołnierskie",
    description: "Ćwiczenie na barki, wykonywane stojąc ze sztangą.",
    picture: require('../GymRad/assets/exercises_icons/shoulder_press.png'),
  },
  {
    id: 8,
    name: "Unoszenie hantli bokiem",
    description: "Izolowane ćwiczenie na boczne aktony barków.",
    picture: require('../GymRad/assets/exercises_icons/lateral_raise.png'),
  },
  {
    id: 9,
    name: "Uginanie ramion ze sztangą",
    description: "Klasyczne ćwiczenie na biceps.",
    picture: require('../GymRad/assets/exercises_icons/bicep_barbell_curl.png'),
  },
  {
    id: 10,
    name: "Prostowanie ramion na wyciągu chwytem linkowym (warkocz)",
    description: "Ćwiczenie izolujące triceps na wyciągu.",
    picture: require('../GymRad/assets/exercises_icons/tricep_rope_pushdown.png'),
  },
  {
    id: 11,
    name: "Deska",
    description: "Ćwiczenie na stabilizację i wzmocnienie mięśni brzucha.",
    picture: require('../GymRad/assets/exercises_icons/plank.png'),
  },
  {
    id: 12,
    name: "Brzuszki",
    description: "Podstawowe ćwiczenie na mięśnie prosty brzucha.",
    picture: require('../GymRad/assets/exercises_icons/situp.png'),
  },
  {
    id: 13,
    name: "Wznosy łydek na maszynie",
    description: "Ćwiczenie wzmacniające łydki.",
    picture: require('../GymRad/assets/exercises_icons/calf_raise.png'),
  },
  {
    id: 14,
    name: "Unoszenie nóg w zwisie",
    description: "Ćwiczenie na dolne partie mięśni brzucha.",
    picture: require('../GymRad/assets/exercises_icons/leg_raise.png'),
  },
  {
    id: 15,
    name: "Face Pull",
    description: "Ćwiczenie na tylny akton barków oraz górną część pleców.",
    picture: require('../GymRad/assets/exercises_icons/face_pull.png'),
  },
  {
    id: 16,
    name: "Wyciskanie hantli na ławce dodatniej",
    description: "Ćwiczenie na górną część klatki piersiowej.",
    picture: require('../GymRad/assets/exercises_icons/Incline_db_press.png'),
  },
  {
    id: 17,
    name: "Wiosłowanie hantlami",
    description: "Buduje mięśnie pleców i poprawia stabilizację.",
    picture: require('../GymRad/assets/exercises_icons/db_row.png'),
  },
  {
    id: 18,
    name: "Przysiady bułgarskie",
    description: "Ćwiczenie jednostronne na uda i pośladki.",
    picture: require('../GymRad/assets/exercises_icons/bulg_split_squat.png'),
  },
  {
    id: 19,
    name: "Swing kettlebell",
    description: "Dynamiczne ćwiczenie angażujące biodra i pośladki.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 20,
    name: "Rozpiętki na ławce",
    description: "Izoluje mięśnie klatki piersiowej.",
    picture: require('../GymRad/assets/exercises_icons/fly.png'),
  },
  {
    id: 21,
    name: "Podciąganie australijskie",
    description: "Łatwiejsza wersja podciągania, angażuje plecy i ramiona.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 22,
    name: "Deska bokiem",
    description: "Ćwiczenie na mięśnie skośne brzucha.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 23,
    name: "Dipy na poręczach",
    description: "Ćwiczenie na tricepsy i klatkę piersiową.",
    picture: require('../GymRad/assets/exercises_icons/dip.png'),
  },
  {
    id: 24,
    name: "Wspięcia na łydki siedząc",
    description: "Izoluje mięśnie łydek.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 25,
    name: "Uginanie nóg leżąc",
    description: "Izolowane ćwiczenie na tylne partie ud.",
    picture: require('../GymRad/assets/exercises_icons/leg_curl_lying.png'),
  },
  {
    id: 26,
    name: "Prostowanie nóg na maszynie",
    description: "Ćwiczenie izolujące przednią część ud.",
    picture: require('../GymRad/assets/exercises_icons/leg_extension.png'),
  },
  {
    id: 27,
    name: "Unoszenie ramion w przód",
    description: "Ćwiczenie na przedni akton barków.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 28,
    name: "Odwodzenie nóg w tył",
    description: "Ćwiczenie na pośladki.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 29,
    name: "Przyciąganie linki wyciągu dolnego do brzucha",
    description: "Buduje mięśnie pleców.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 30,
    name: "Wiosłowanie jednorącz",
    description: "Izoluje jedną stronę pleców.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 31,
    name: "Hip Thrust",
    description: "Ćwiczenie wzmacniające pośladki i tylną taśmę mięśniową.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 32,
    name: "Wznosy barków (shrugs)",
    description: "Ćwiczenie na mięśnie czworoboczne (kaptury).",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 33,
    name: "Przysiady sumo",
    description: "Ćwiczenie na wewnętrzną stronę ud i pośladki.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 34,
    name: "Przenoszenie hantla za głowę leżąc",
    description: "Ćwiczenie rozciągające mięśnie klatki i grzbietu.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 35,
    name: "Mountain climbers",
    description: "Ćwiczenie cardio angażujące całe ciało.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 36,
    name: "Unoszenie bioder leżąc",
    description: "Ćwiczenie na pośladki i dolne partie pleców.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 37,
    name: "Plank z unoszeniem nogi",
    description: "Wzmacnia brzuch i pośladki.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 38,
    name: "Prostowanie ramion z hantlem zza głowy",
    description: "Ćwiczenie na tricepsy.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 39,
    name: "Uginanie młotkowe hantli",
    description: "Wzmacnia mięśnie ramion i przedramion.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 40,
    name: "Rozpiętki na maszynie",
    description: "Izoluje klatkę piersiową.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 41,
    name: "Przysiad z hantlami nad głową",
    description: "Angażuje nogi, barki i brzuch.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 42,
    name: "Burpees",
    description: "Dynamiczne ćwiczenie całego ciała.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 43,
    name: "Skakanka",
    description: "Ćwiczenie cardio poprawiające kondycję i zwinność.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 44,
    name: "Wykroki chodzone",
    description: "Buduje siłę i wytrzymałość nóg.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 45,
    name: "Uginanie nadgarstków siedząc",
    description: "Ćwiczenie na mięśnie przedramion.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 46,
    name: "Unoszenie nóg leżąc",
    description: "Ćwiczenie na dolną partię brzucha.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 47,
    name: "Przyciąganie kolan do klatki na poręczach",
    description: "Wzmacnia mięśnie brzucha.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 48,
    name: "Odwrotne pompki (triceps dips)",
    description: "Ćwiczenie na tricepsy, wykonywane na ławce.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 49,
    name: "Kettlebell goblet squat",
    description: "Przysiad z kettlem trzymanym przy klatce piersiowej.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
  {
    id: 50,
    name: "Renegade row",
    description: "Wiosłowanie z podporu, angażujące plecy i core.",
    // picture: require('../GymRad/assets/exercises_icons/'),
  },
];
